databases:
  - name: easycart_rails_db
    databaseName: easycart_rails_production
    user: easycart_rails
    plan: free

services:
  - type: web
    name: easycart_rails
    env: docker
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: easycart_rails_db
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1" # Keep low for free tier
